name: example
description: "App de exemplo e testes para o WGC Design System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  flutter:
    sdk: flutter

  # Importando os módulos locais como pacotes independentes
  wgc_components:
    path: ../components
  wgc_templates:
    path: ../templates

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Ajustado para versão estável compatível
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # O App de exemplo pode ter seus próprios assets se necessário
  # assets:
  #   - assets/images/