name: wgc_components
description: "Biblioteca de componentes básicos do WGC Design System"
version: 0.0.1
publish_to: 'none' # Impede publicação acidental no pub.dev

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wgc_core_ds:
    path: ../core_ds

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ativando Assets para o pacote de componentes
  assets:
    - assets/images/
    - assets/icons/

  # Ativando Fonts para o pacote de componentes
#  fonts:
#    - family: WGCFontCustom
#      fonts:
#        - asset: assets/fonts/Custom-Regular.ttf
#        - asset: assets/fonts/Custom-Bold.ttf
#          weight: 700